# PATH
export PATH="/bin:/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/X11/bin"
export CDPATH=.:~:~/Projects:~/Projects/labs:~/Projects/works:~/Projects/personal

source $HOME/.bash/scripts/export.sh
source $HOME/.bash/scripts/alias.sh
source $HOME/.bash/scripts/options.sh
source $HOME/.bash/scripts/utils.sh

source $HOME/.bash/scripts/prompt.sh
