# Path
export PATH="/bin:/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/X11/bin:$HOME/.rbenv/bin"
export CDPATH=.:~:~/Projects:~/Projects/labs:~/Projects/works

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

source `brew --prefix`/etc/bash_completion.d/git-completion.bash
source `brew --prefix`/etc/bash_completion.d/git-prompt.sh

source $HOME/.bash/scripts/export.sh
source $HOME/.bash/scripts/alias.sh
source $HOME/.bash/scripts/options.sh
source $HOME/.bash/scripts/utils.sh

source $HOME/.bash/scripts/prompt.sh
